add service to retrieve data
safir-medjeber/compareTo pull request #1
Opened 2017-12-29 20:49 UTC by safir-medjeber

2017-12-29 22:44 UTC, marc-gedik requested changes

2017-12-29 22:44 UTC, marc-gedik commented on src/app/app.module.ts
> +    HttpClient,
Y'a besoin d'ajouter le `HttpClient` là 🤔 ?

2017-12-29 22:44 UTC, marc-gedik commented on src/pages/main-menu/main-menu.ts
> +    this.items = this.itemService.loadData();
Je refuse, pourquoi tu recuperes tous les items?

2017-12-29 22:44 UTC, marc-gedik commented on src/services/item.service.ts
> +    this.loadFile();
C'est une fonction a effet de bord ça c'est pas cool 👎

2017-12-29 22:44 UTC, marc-gedik commented on src/services/item.service.ts
> +    this.loadFile();
Au lieu de retourner `Item[]` retourne un `Observable<Item[]>`

2017-12-30 09:18 UTC, safir-medjeber commented on src/app/app.module.ts
> +    HttpClient,
![bitmoji](https://render.bitstrips.com/v2/cpanel/bea8cce1-c2d2-4631-8975-65c26599d82d-18ba1ee3-264f-473a-bdcd-067524faf702-v1.png?transparent=1&palette=1&width=246) il ne sert à rien

2017-12-30 09:20 UTC, safir-medjeber commented on src/pages/main-menu/main-menu.ts
> +    this.items = this.itemService.loadData();
c'est pour un test: mais pourquoi ne pas tout charger en mémoire une seule fois puis faire des filtres ?

2017-12-30 09:23 UTC, safir-medjeber commented on src/app/app.module.ts
> +    HttpClient,
![bitmoji](https://render.bitstrips.com/v2/cpanel/55c09522-48c7-4597-bf8d-63cd5f94649d-18ba1ee3-264f-473a-bdcd-067524faf702-v1.png?transparent=1&palette=1&width=246)

2018-01-02 21:35 UTC, marc-gedik approved these changes

2018-01-02 21:37 UTC, merged